//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hangmanGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hangmanGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept_button {
            get {
                return ResourceManager.GetString("Accept_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account was created successfully..
        /// </summary>
        public static string AccountRegistrationMessage {
            get {
                return ResourceManager.GetString("AccountRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account registration.
        /// </summary>
        public static string AccountRegistrationMessageTitle {
            get {
                return ResourceManager.GetString("AccountRegistrationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accumulated Score.
        /// </summary>
        public static string AccumulatedScore {
            get {
                return ResourceManager.GetString("AccumulatedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BEST SCORES.
        /// </summary>
        public static string BestScores {
            get {
                return ResourceManager.GetString("BestScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change.
        /// </summary>
        public static string Change_Button {
            get {
                return ResourceManager.GetString("Change_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePassword_Button {
            get {
                return ResourceManager.GetString("ChangePassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password was changed successfully..
        /// </summary>
        public static string ChangePasswordMessage {
            get {
                return ResourceManager.GetString("ChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePasswordMessageTitle {
            get {
                return ResourceManager.GetString("ChangePasswordMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation Code: .
        /// </summary>
        public static string ConfirmationCode {
            get {
                return ResourceManager.GetString("ConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm New Password: .
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password: .
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password: .
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string DeleteAccount_Button {
            get {
                return ResourceManager.GetString("DeleteAccount_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account was successfully deleted..
        /// </summary>
        public static string DeleteAccountMessage {
            get {
                return ResourceManager.GetString("DeleteAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Account.
        /// </summary>
        public static string DeleteAccountMessageTitle {
            get {
                return ResourceManager.GetString("DeleteAccountMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email: .
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email not found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email you entered does not correspond to that of any active account.
        /// </summary>
        public static string EmailNotFoundDetails {
            get {
                return ResourceManager.GetString("EmailNotFoundDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You entered invalid credentials. Please enter correct data or register..
        /// </summary>
        public static string EnteredWrongCredentials {
            get {
                return ResourceManager.GetString("EnteredWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter only 6-digit numbers..
        /// </summary>
        public static string ErrorCodeConfirmation {
            get {
                return ResourceManager.GetString("ErrorCodeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code you entered is not correct. Please enter the one that was sent to your email.
        /// </summary>
        public static string ErrorCodeDetails {
            get {
                return ResourceManager.GetString("ErrorCodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password not modified.
        /// </summary>
        public static string ErrorDataBase {
            get {
                return ResourceManager.GetString("ErrorDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no connection to the database. Please try again later.
        /// </summary>
        public static string ErrorDataBaseDetails {
            get {
                return ResourceManager.GetString("ErrorDataBaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a valid email structure &quot;maria_12@gmail.com&quot;..
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter only letters..
        /// </summary>
        public static string ErrorNameComplete {
            get {
                return ResourceManager.GetString("ErrorNameComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter only letters and numbers..
        /// </summary>
        public static string ErrorNickName {
            get {
                return ResourceManager.GetString("ErrorNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter letters A-Z or a-z, 0-9 and characters @_#. Length (8-15)..
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the correct confirmation code..
        /// </summary>
        public static string IncorrectCodeMessage {
            get {
                return ResourceManager.GetString("IncorrectCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect confirmation code.
        /// </summary>
        public static string IncorrectCodeMessageTitle {
            get {
                return ResourceManager.GetString("IncorrectCodeMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter correct data in the fields marked in red..
        /// </summary>
        public static string IncorrectDataMessage {
            get {
                return ResourceManager.GetString("IncorrectDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect Data.
        /// </summary>
        public static string IncorrectDataMessageTitle {
            get {
                return ResourceManager.GetString("IncorrectDataMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect Email.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email you entered does not correspond to the structure of an email. Please enter a valid email.
        /// </summary>
        public static string IncorrectEmailDetails {
            get {
                return ResourceManager.GetString("IncorrectEmailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect Passwords.
        /// </summary>
        public static string IncorrectPasswords {
            get {
                return ResourceManager.GetString("IncorrectPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code you entered is not correct. Please enter the one that was sent to your email.
        /// </summary>
        public static string IncorrectPasswordsDetails {
            get {
                return ResourceManager.GetString("IncorrectPasswordsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language: .
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name: .
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        public static string LogOut_Button {
            get {
                return ResourceManager.GetString("LogOut_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please check your email to confirm your email and continue with the account creation process..
        /// </summary>
        public static string MessageConfirmation {
            get {
                return ResourceManager.GetString("MessageConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        public static string Modify_Button {
            get {
                return ResourceManager.GetString("Modify_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data was successfully modified..
        /// </summary>
        public static string ModifyAccountMessage {
            get {
                return ResourceManager.GetString("ModifyAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Account.
        /// </summary>
        public static string ModifyAccountMessageTitle {
            get {
                return ResourceManager.GetString("ModifyAccountMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please modify at least one data..
        /// </summary>
        public static string ModifyLeastDataMessage {
            get {
                return ResourceManager.GetString("ModifyLeastDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Data.
        /// </summary>
        public static string ModifyLeastDataMessageTile {
            get {
                return ResourceManager.GetString("ModifyLeastDataMessageTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name: .
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password: .
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NickName: .
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account was not registered, please try again later..
        /// </summary>
        public static string NoAccountRegisteredMessage {
            get {
                return ResourceManager.GetString("NoAccountRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password was not changed, please try again later..
        /// </summary>
        public static string NoChangePasswordMessage {
            get {
                return ResourceManager.GetString("NoChangePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account was not deleted. Please try again later..
        /// </summary>
        public static string NoDeleteAccountMessage {
            get {
                return ResourceManager.GetString("NoDeleteAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The data was not modified, please try again later..
        /// </summary>
        public static string NoModifyAccountMessage {
            get {
                return ResourceManager.GetString("NoModifyAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password: .
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed successfully.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password has been modified successfully you can now enter the game.
        /// </summary>
        public static string PasswordChangedDetails {
            get {
                return ResourceManager.GetString("PasswordChangedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Play_Button {
            get {
                return ResourceManager.GetString("Play_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the recovery code sent to your email:.
        /// </summary>
        public static string RecoverCode {
            get {
                return ResourceManager.GetString("RecoverCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send recovery code.
        /// </summary>
        public static string RecoveryCode_Button {
            get {
                return ResourceManager.GetString("RecoveryCode_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is already registered. Please change it..
        /// </summary>
        public static string RegisteredEmailMessage {
            get {
                return ResourceManager.GetString("RegisteredEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The nickname and email are already registered. Please change them..
        /// </summary>
        public static string RegisteredEmailNickNameMessage {
            get {
                return ResourceManager.GetString("RegisteredEmailNickNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The nickname is already registered. Please change it..
        /// </summary>
        public static string RegisteredNickNameMessage {
            get {
                return ResourceManager.GetString("RegisteredNickNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeated Data.
        /// </summary>
        public static string RepeatedDataMessageTitle {
            get {
                return ResourceManager.GetString("RepeatedDataMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your score is:.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Confirmation Code.
        /// </summary>
        public static string SendConfirmation_Button {
            get {
                return ResourceManager.GetString("SendConfirmation_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string SendMessage_Button {
            get {
                return ResourceManager.GetString("SendMessage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound: .
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string TitleChangePassword {
            get {
                return ResourceManager.GetString("TitleChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Account.
        /// </summary>
        public static string TitleDeleteAccount {
            get {
                return ResourceManager.GetString("TitleDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email confirmation.
        /// </summary>
        public static string TitleEmailConfirmation {
            get {
                return ResourceManager.GetString("TitleEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hangman Game.
        /// </summary>
        public static string TitleGame {
            get {
                return ResourceManager.GetString("TitleGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string TitleLogIn {
            get {
                return ResourceManager.GetString("TitleLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lost My Password.
        /// </summary>
        public static string TitleLostMyPassword {
            get {
                return ResourceManager.GetString("TitleLostMyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify Account.
        /// </summary>
        public static string TitleModifyAccount {
            get {
                return ResourceManager.GetString("TitleModifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HangmanGame.
        /// </summary>
        public static string TitlePlay {
            get {
                return ResourceManager.GetString("TitlePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Account.
        /// </summary>
        public static string TitleRecoverAccount {
            get {
                return ResourceManager.GetString("TitleRecoverAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Account.
        /// </summary>
        public static string TitleRegistry {
            get {
                return ResourceManager.GetString("TitleRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting.
        /// </summary>
        public static string TitleSetting {
            get {
                return ResourceManager.GetString("TitleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Account.
        /// </summary>
        public static string UpdateAccount_Button {
            get {
                return ResourceManager.GetString("UpdateAccount_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate your Email:.
        /// </summary>
        public static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify your new password:.
        /// </summary>
        public static string ValidatePassword {
            get {
                return ResourceManager.GetString("ValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong credentials.
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
